### ISSUE TITLE
`fix_to_zero()`: Check identification in the generated model

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semlrtp#9]
# To-Dos

- [x] Write a test.
- [x] Create a dataset and model which would have that problem.
- [x] Revise `fix_to_zero()` to detect this problem.
- [x] ~Check which other functions need to be revised to handle parameters for which LRT p-value cannot be computed.~ This will be handled in #18 .

# Status

Done in 0.0.0.9015:  Check VCOV for identification problem. See #23 

# Note

The model with one parameter constrained to zero may not be identified. Check this in `fix_to_zero().
